// Mocks generated by Mockito 5.4.0 from annotations
// in login_micro_app/test/resources/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:login_micro_app/login/data/models/default_login_request_model.dart' as _i8;
import 'package:login_micro_app/login/data/models/default_login_response_model.dart' as _i3;
import 'package:login_micro_app/login/data/services/auth_service.dart' as _i7;
import 'package:login_micro_app/login/domain/entities/default_login_entity.dart' as _i2;
import 'package:login_micro_app/login/domain/repositories/auth_repository.dart' as _i4;
import 'package:login_micro_app/login/domain/usecases/default_login_usecase.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDefaultLoginEntity_0 extends _i1.SmartFake implements _i2.DefaultLoginEntity {
  _FakeDefaultLoginEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDefaultLoginResponseModel_1 extends _i1.SmartFake implements _i3.DefaultLoginResponseModel {
  _FakeDefaultLoginResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.DefaultLoginEntity> defaultLogin(_i6.DefaultLoginUsecaseParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #defaultLogin,
          [params],
        ),
        returnValue: _i5.Future<_i2.DefaultLoginEntity>.value(_FakeDefaultLoginEntity_0(
          this,
          Invocation.method(
            #defaultLogin,
            [params],
          ),
        )),
      ) as _i5.Future<_i2.DefaultLoginEntity>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.DefaultLoginResponseModel> defaultLogin(_i8.DefaultLoginRequestModel? requestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #defaultLogin,
          [requestModel],
        ),
        returnValue: _i5.Future<_i3.DefaultLoginResponseModel>.value(_FakeDefaultLoginResponseModel_1(
          this,
          Invocation.method(
            #defaultLogin,
            [requestModel],
          ),
        )),
      ) as _i5.Future<_i3.DefaultLoginResponseModel>);
}
